### ISSUE TITLE
httpclient.cpp error

### ISSUE THREAD

**Issue by interas99** [CynCeyd/TS3BridgeTTT#2]
Hey,
if trouble with your Bridge. I think that the Bridge is a very nice idea but it doesnt work on my Server :(

The Server starts fine and everything is working except the bridge.
The console shows this error every ~5 sec: 

`httpclient.cpp (2374) : Assertion Failed: pHost && *pHost`

I´ve set the two convars in the Server.cfg and configurated the PHP file on my Webserver.

I hope you can halp me.

Best regards

Interas

P.S. I hope you can understand me despite my bad english :)

**Comment by CynCeyd** [comment]
Hi there,

unfortunately I'm currently in vacation and cannot research on this issue. I will resolve this when I have returned in about four weeks, okay?

Greetings
Nicolas

I could unterstand you without any problems, by the way ;-).

**Comment by CynCeyd** [comment]
I remembered that there was a similar issue a year ago. Did you perhaps forget to add " to the beginning and end of the url and api key? For instance, the url should look like this in the server.cfg:

ttt_ts3_bridge_url "http://example.com/ts3bridge.php"

**Comment by interas99** [comment]
Hi there,

That was the issue.... Thank you for you quick answer.
I wish you a nice vacation.

Greetings
Interas
