### ISSUE TITLE
Benötige Hilfe

### ISSUE THREAD

**Issue by TheFrodo** [CynCeyd/TS3BridgeTTT#8]
Hey,

Ich habe alles so wie es auf der Seite beschreiben ist installiert und konfiguriert. Nur leider sagt er mir sobald ich den Gmod Server betrete: The user  using the ip address  and Steam id STEAM_0:0:58555226. could not be found

Kannst du mir irgendwie helfen?

**Comment by CynCeyd** [comment]
Versuche ggf. das Workshop-Plugin zu entfernen und manuell die ts3bridge.lua in den Ordner lua/autorun ([Die aus dem Repository](https://github.com/CynCeyd/TS3BridgeTTT/tree/master/GMod/lua/autorun)) zu kopieren. Ich hab schon vor Ewigkeiten beide Teile so gut wie neu geschrieben, aber ich komm nicht dazu das auch im Workshop hochzuladen.

Wenns danach nicht funktioniert, können wir gern weitergucken.

**Comment by TheFrodo** [comment]
Heii,

Das habe ich jetzt gemacht, der Log sagt mir jetzt aber nach dem das geladen wurde

ServerLog: [TS3 Bridge TTT] Loading TeamSpeak 3 bridge
HTTP failed - ISteamHTTP isn't available!

**Comment by TheFrodo** [comment]
Alles klar hat sich erledigt. Jetzt funktioniert es
